# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True)),
                ('mist', models.BooleanField(default=False)),
                ('fan', models.BooleanField(default=False)),
                ('heat', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('light', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique_for_date=True)),
                ('t_amb', models.DecimalField(decimal_places=2, max_digits=2)),
                ('t_obj', models.DecimalField(decimal_places=2, max_digits=2)),
                ('rh', models.PositiveIntegerField()),
                ('hpa', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lux', models.PositiveIntegerField()),
                ('wind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('water', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
