# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchid_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='hpa',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='t_amb',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='t_obj',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
