# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchid_app', '0002_auto_20170304_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='t_amb',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='t_obj',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='water',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='wind',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
