# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchid_app', '0003_auto_20170304_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
