# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchid_app', '0004_auto_20170314_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
